name: Pull Request VRT

on: [ pull_request ]

concurrency:
  group: pull-request-vrt-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: write # for yumemi-inc/comment-pull-request

env:
  expect-artifact: vrt-${{ github.event.pull_request.base.sha }}-expected
  actual-artifact: vrt-${{ github.event.pull_request.head.sha }}-actual

# TODO cache screenshots
jobs:
  take-expect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Base Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - uses: yumemi-inc/setup-java-gradle@v2

      - name: Take Expect Screenshot from Base Branch
        run: ./gradlew recordRoborazziDebug
      - run: mkdir -p .reg && mv build/roborazzi-outputs .reg && mv .reg/roborazzi-outputs .reg/expected

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: ${{ env.expect-artifact }}
          path: |
            .reg/expected

  take-actual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Head Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          clean: false
      - uses: yumemi-inc/setup-java-gradle@v2

      - name: Take Actual Screenshot from Head Branch
        run: ./gradlew recordRoborazziDebug
      - run: tree build/roborazzi-outputs && cat ui/src/main/kotlin/your/projectPackage/ui/component/AppButton.kt

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: ${{ env.actual-artifact }}
          path: |
            build/roborazzi-outputs

  report:
    needs: [ take-expect, take-actual ]
    runs-on: ubuntu-latest
    permissions:
      contents: write # for peaceiris/actions-gh-pages
      pull-requests: write # for yumemi-inc/comment-pull-request
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - uses: actions/setup-node@v4 # for reg-suit
        with:
          node-version: 22.x
      - run: npm i

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.expect-artifact }}
          path: .reg/expected
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.actual-artifact }}
          path: build/roborazzi-outputs

      - run: npx reg-suit run

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.reg
          destination_dir: ./pr/${{ github.event.pull_request.number }}/vrt/
          keep_files: true

      - id: get_outputs
        run: |
          # items count
          newItems=$(jq ".newItems | length" .reg/out.json)
          echo "newItems=$newItems" >> $GITHUB_OUTPUT

          diffItems=$(jq ".diffItems | length" .reg/out.json)
          echo "diffItems=$diffItems" >> $GITHUB_OUTPUT

          deletedItems=$(jq ".deletedItems | length" .reg/out.json)
          echo "deletedItems=$deletedItems" >> $GITHUB_OUTPUT

          hasChanges=$([ "$newItems" -ne 0 ] || [ "$diffItems" -ne 0 ] || [ "$deletedItems" -ne 0 ] && echo true || echo false)
          echo "hasChanges=$hasChanges" >> $GITHUB_OUTPUT

          echo "newItems=$newItems diffItems=$diffItems deletedItems=$deletedItems hasChanges=$hasChanges"

          # pages_url
          owner_name=${{ github.repository_owner }}
          repo_name=$(echo ${{ github.repository }} | cut -d'/' -f2)
          pages_url="https://$owner_name.github.io/$repo_name/pr/${{ github.event.pull_request.number }}/vrt"
          echo "owner_name=$owner_name repo_name=$repo_name pages_url=$pages_url"

          echo "pages_url=$pages_url" >> $GITHUB_OUTPUT

          # images markdown table
          images_markdown=""

          table_rows() {
              target=$1
              id_prefix=${2:-$1}-

              for item in $(jq -r ".${target}Items[]" .reg/out.json); do
                  images_markdown="${images_markdown}<!-- [$target] $(basename $item) -->\n"
                  images_markdown="${images_markdown}<table>\n"

                  # header title
                  images_markdown="${images_markdown}<thead>\n"

                  if [ "$target" = "diff" ]; then
                      images_markdown="${images_markdown}<tr><td colspan='3'>\n\n"
                      images_markdown="${images_markdown}[**[${target}] $(basename $item)**]($pages_url?id=$id_prefix$item)"
                      images_markdown="${images_markdown}\n\n</td></tr>\n"
                  else
                      images_markdown="${images_markdown}<tr><td>\n\n"
                      images_markdown="${images_markdown}[**[${target}] $(basename $item)**]($pages_url?id=$id_prefix$item)"
                      images_markdown="${images_markdown}\n\n</td></tr>\n"
                  fi

                  # header before/diff/after
                  images_markdown="${images_markdown}<tr>\n"
                  if [ "$target" != "new" ]; then
                      images_markdown="${images_markdown}<td align="center">before</td>\n"
                  fi
                  if [ "$target" = "diff" ]; then
                      images_markdown="${images_markdown}<td align="center">diff</td>\n"
                  fi
                  if [ "$target" != "deleted" ]; then
                      images_markdown="${images_markdown}<td align="center">after</td>\n"
                  fi

                  images_markdown="${images_markdown}</thead>\n"

                  # body
                  images_markdown="${images_markdown}<tbody>\n"

                  if [ "$target" = "new" ]; then
                      images_markdown="${images_markdown}<tr>\n"
                      images_markdown="${images_markdown}<td align=center> <img src="$pages_url/actual/${item}" width="200" /> </td>\n"
                      images_markdown="${images_markdown}</tr>\n"
                  fi
                  if [ "$target" = "deleted" ]; then
                      images_markdown="${images_markdown}<tr>\n"
                      images_markdown="${images_markdown}<td align=center> <img src="$pages_url/expected/${item}" width="200" /> </td>\n"
                      images_markdown="${images_markdown}</tr>\n"
                  fi
                  if [ "$target" = "diff" ]; then
                      images_markdown="${images_markdown}<tr>\n"
                      images_markdown="${images_markdown}<td align=center> <img src="$pages_url/expected/${item}" width="200" /> </td>\n"
                      images_markdown="${images_markdown}<td align=center> <img src="$pages_url/diff/${item}" width="200" /> </td>\n"
                      images_markdown="${images_markdown}<td align=center> <img src="$pages_url/actual/${item}" width="200" /> </td>\n"
                      images_markdown="${images_markdown}</tr>\n"
                  fi

                  images_markdown="${images_markdown}</tbody>\n"

                  images_markdown="${images_markdown}</table>\n\n"
              done
          }

          table_rows "new"
          table_rows "diff" "changed"
          table_rows "deleted"

          echo "images_markdown=$images_markdown" >> $GITHUB_OUTPUT

      - name: Comment Pull Request
        uses: yumemi-inc/comment-pull-request@v1
        with:
          comment: |
            #### VRT Result

            ${{
              steps.get_outputs.outputs.hasChanges == 'true'
                && '> [!CAUTION]\n> There are visual changes 🔥'
                || '> [!TIP]\n> No visual changes 👍'
            }}

            For more information, see [VRT report](${{ steps.get_outputs.outputs.pages_url }}).

            | type | diff files |
            |---|---|
            | [new](${{ steps.get_outputs.outputs.pages_url }}#new)    | [${{ steps.get_outputs.outputs.newItems }}](${{ steps.get_outputs.outputs.pages_url }}#new) |
            | [diff](${{ steps.get_outputs.outputs.pages_url }}#changed)   | [${{ steps.get_outputs.outputs.diffItems }}](${{ steps.get_outputs.outputs.pages_url }}#changed) |
            | [delete](${{ steps.get_outputs.outputs.pages_url }}#deleted) | [${{ steps.get_outputs.outputs.deletedItems }}](${{ steps.get_outputs.outputs.pages_url }}#deleted) |

            ${{
              steps.get_outputs.outputs.hasChanges == 'true'
                && format(
                  '<details>\n<summary>Screenshots</summary>\n\n{0}\n\n</details>',
                  steps.get_outputs.outputs.images_markdown
                )
                || ''
            }}

      - name: Update PR Body
        run: |
          pr_body=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)

          current_date=$(date "+%Y-%m-%d %H:%M:%S")
          commit_sha="${{ github.event.pull_request.head.sha }}"
          commit_short=${commit_sha:0:7}
          screenshot_info="<\!-- {{screenshots}} -->\n\n**最終更新:** ${current_date}\n**コミット:** ${commit_short}\n\n${{ steps.get_outputs.outputs.images_markdown }}"
          screenshot_info_with_toggle="<details>\n<summary>Screenshots</summary>\n\n${screenshot_info}\n\n</details>"

          updated_pr_body=$pr_body
          updated_pr_body="${updated_pr_body/<\!-- {{screenshots}} -->/$screenshot_info}"
          updated_pr_body="${updated_pr_body/<\!-- {{screenshots-with-toggle}} -->/$screenshot_info_with_toggle}"

          echo "$updated_pr_body" | gh pr edit ${{ github.event.pull_request.number }} --body-file -
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
