name: Pull Request Check

on: [ pull_request ]

permissions:
  pull-requests: write # for yumemi-inc/comment-pull-request

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - uses: reviewdog/action-setup@v1
      - uses: actions/setup-node@v4 # for merge sarif
      - run: npm i -g @microsoft/sarif-multitool

      - name: Android Lint
        run: ./gradlew lint --continue

      - name: Merge sarif files
        if: ${{ !cancelled() }}
        run: |
          sarifs=$(find . -regex "^./build/build-outputs/.*/android-lint-report/.*\.sarif$" | xargs echo)
          echo $sarifs
          npx @microsoft/sarif-multitool merge $sarifs --output-file merged-android-lint.sarif
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1 # refs: https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in
      - if: ${{ !cancelled() }}
        run: |
          reviewdog \
            -name="Android Lint" \
            -f=sarif \
            -reporter=github-pr-review \
            -filter-mode=file \
            < merged-android-lint.sarif
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - uses: reviewdog/action-setup@v1
      - uses: actions/setup-node@v4 # for merge sarif
      - run: npm i -g @microsoft/sarif-multitool

      - name: Ktlint
        run: ./gradlew ktlintCheck --continue

      - name: Merge sarif files
        if: ${{ !cancelled() }}
        run: |
          sarifs=$(find . -regex "^./build/build-outputs/.*/ktlint-report/.*\.sarif$" | xargs echo)
          echo $sarifs
          npx @microsoft/sarif-multitool merge $sarifs --output-file merged-android-lint.sarif
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1 # refs: https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in
      - if: ${{ !cancelled() }}
        run: |
          reviewdog \
            -name="Android Lint" \
            -f=sarif \
            -reporter=github-pr-review \
            -filter-mode=file \
            < merged-android-lint.sarif
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - run: ./gradlew test
      - uses: yumemi-inc/comment-pull-request@v1
        if: cancelled() != true
        with:
          comment-if-failure: |
            > [!CAUTION]
            > There was a problem with the **Unit Test** check. See details [here](${{ env.LOG_URL }}).

  vrt:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for peaceiris/actions-gh-pages
      pull-requests: write # for yumemi-inc/comment-pull-request
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - uses: actions/setup-node@v4 # for reg-suit
        with:
          node-version: 20.x
      - run: npm i

      - name: Checkout Base Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - name: Take Expect Screenshot from Base Branch
        run: ./gradlew recordRoborazziDebug
      - run: mkdir -p .reg && mv build/roborazzi-outputs .reg && mv .reg/roborazzi-outputs .reg/expected
      - run: tree .reg # for debug

      - name: Checkout Head Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Take Actual Screenshot from Head Branch
        run: ./gradlew recordRoborazziDebug
      - run: mkdir -p .reg && mv build/roborazzi-outputs .reg && mv .reg/roborazzi-outputs .reg/actual
      - run: tree .reg # for debug

      - id: reg-suit
        run: npx reg-suit run

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.reg
          destination_dir: ./pr/${{ github.event.pull_request.number }}/vrt/
          keep_files: true

      - run: |
          newItems=$(jq ".newItems | length" .reg/out.json)
          echo "newItems=$newItems" >> $GITHUB_OUTPUT

          diffItems=$(jq ".diffItems | length" .reg/out.json)
          echo "diffItems=$diffItems" >> $GITHUB_OUTPUT

          deletedItems=$(jq ".deletedItems | length" .reg/out.json)
          echo "deletedItems=$deletedItems" >> $GITHUB_OUTPUT

          echo "newItems=$newItems diffItems=$diffItems deletedItems=$deletedItems"

      - id: get_pages_url
        run: |
          owner_name=${{ github.repository_owner }}
          repo_name=$(echo ${{ github.repository }} | cut -d'/' -f2)
          pages_url="https://$owner_name.github.io/$repo_name/"
          echo "owner_name=$owner_name repo_name=$repo_name pages_url=$pages_url"
          echo "pages_url=$pages_url" >> $GITHUB_OUTPUT
      - uses: yumemi-inc/comment-pull-request@v1
        with:
          comment: |
            ### VRT

            ${{
              (
                steps.reg-suit.outputs.newItems != '0' ||
                  steps.reg-suit.outputs.diffItems != '0' ||
                  steps.reg-suit.outputs.deletedItems != '0'
              ) && '> [!CAUTION]\n> There are visual changes 🔥'
                || '> [!TIP]\n> No visual changes 👍'
            }}

            See [VRT report](${{ steps.get_pages_url.outputs.pages_url }}).

            #### Summary

            | | |
            |---|---|
            | new    | ${{ steps.reg-suit.outputs.newItems }} |
            | diff   | ${{ steps.reg-suit.outputs.diffItems }} |
            | delete | ${{ steps.reg-suit.outputs.deletedItems }} |

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variants:
          - Debug
          - Release
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - run: ./gradlew :app:assemble${{ matrix.variants }}
