name: Pull Request Check

on: [ pull_request ]

permissions:
  pull-requests: write

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - uses: reviewdog/action-setup@v1
      - uses: actions/setup-node@v4 # for merge sarif
      - run: npm i -g @microsoft/sarif-multitool

      - name: Android Lint
        run: ./gradlew lint --continue

      - name: Merge sarif files
        if: ${{ !cancelled() }}
        run: |
          sarifs=$(find . -regex "^./build/build-outputs/.*/android-lint-report/.*\.sarif$" | xargs echo)
          echo $sarifs
          npx @microsoft/sarif-multitool merge $sarifs --output-file merged-android-lint.sarif
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1 # refs: https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in
      - if: ${{ !cancelled() }}
        run: |
          reviewdog \
            -name="Android Lint" \
            -f=sarif \
            -reporter=github-pr-review \
            -filter-mode=file \
            < merged-android-lint.sarif
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - uses: reviewdog/action-setup@v1
      - uses: actions/setup-node@v4 # for merge sarif
      - run: npm i -g @microsoft/sarif-multitool

      - name: Ktlint
        run: ./gradlew ktlintCheck --continue

      - name: Merge sarif files
        if: ${{ !cancelled() }}
        run: |
          sarifs=$(find . -regex "^./build/build-outputs/.*/ktlint-report/.*\.sarif$" | xargs echo)
          echo $sarifs
          npx @microsoft/sarif-multitool merge $sarifs --output-file merged-android-lint.sarif
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1 # refs: https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in
      - if: ${{ !cancelled() }}
        run: |
          reviewdog \
            -name="Android Lint" \
            -f=sarif \
            -reporter=github-pr-review \
            -filter-mode=file \
            < merged-android-lint.sarif
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - run: ./gradlew test
      - uses: yumemi-inc/comment-pull-request@v1
        if: cancelled() != true
        with:
          comment-if-failure: |
            > [!CAUTION]
            > There was a problem with the **Unit Test** check. See details [here](${{ env.LOG_URL }}).

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variants:
          - Debug
          - Release
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v2
      - run: ./gradlew :app:assemble${{ matrix.variants }}
