name: Pull Request Check

on: [pull_request]

concurrency:
  group: pull-request-check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: write # for yumemi-inc/comment-pull-request

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v3
        with:
          cache-read-only: false
      - uses: reviewdog/action-setup@v1
      - uses: actions/setup-node@v4 # for merge sarif
      - run: npm i -g @microsoft/sarif-multitool

      - name: Android Lint
        run: ./gradlew lint --continue

      - name: Merge sarif files
        if: ${{ !cancelled() }}
        run: |
          sarifs=$(find . -regex "^./build/build-outputs/.*/android-lint-report/.*\.sarif$" | xargs echo)
          echo $sarifs
          npx @microsoft/sarif-multitool merge $sarifs --output-file merged-android-lint.sarif
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1 # refs: https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in
      - if: ${{ !cancelled() }}
        run: |
          reviewdog \
            -name="Android Lint" \
            -f=sarif \
            -reporter=github-pr-review \
            -filter-mode=file \
            < merged-android-lint.sarif
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: yumemi-inc/comment-pull-request@v1
        if: cancelled() != true
        with:
          comment-if-failure: |
            > [!CAUTION]
            > There was a problem with the **Android Lint** check. See details [here](${{ env.LOG_URL }}) or run `./gradlew lint` in local.

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v3
        with:
          cache-read-only: false
      - uses: reviewdog/action-setup@v1
      - uses: actions/setup-node@v4 # for merge sarif
      - run: npm i -g @microsoft/sarif-multitool

      - name: Ktlint
        run: ./gradlew ktlintCheck --continue

      - name: Merge sarif files
        if: ${{ !cancelled() }}
        run: |
          sarifs=$(find . -regex "^./build/build-outputs/.*/ktlint-report/.*\.sarif$" | xargs echo)
          echo $sarifs
          npx @microsoft/sarif-multitool merge $sarifs --output-file merged-ktlint.sarif
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1 # refs: https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in
      - if: ${{ !cancelled() }}
        run: |
          reviewdog \
            -name="Ktlint" \
            -f=sarif \
            -reporter=github-pr-review \
            -filter-mode=file \
            < merged-ktlint.sarif
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: yumemi-inc/comment-pull-request@v1
        if: cancelled() != true
        with:
          comment-if-failure: |
            > [!CAUTION]
            > There was a problem with the **Ktlint** check. See details [here](${{ env.LOG_URL }}) or run `./gradlew ktlintCheck` in local.

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v3
        with:
          cache-read-only: false
      - uses: reviewdog/action-setup@v1
      - uses: actions/setup-node@v4 # for merge sarif
      - run: npm i -g @microsoft/sarif-multitool

      - name: detekt
        run: ./gradlew detekt

      - name: Merge sarif files
        if: ${{ !cancelled() }}
        run: |
          sarifs=$(find . -regex "^.*/reports/detekt/.*\.sarif$" | xargs echo)
          echo $sarifs
          npx @microsoft/sarif-multitool merge $sarifs --output-file merged-detekt.sarif
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1 # refs: https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in
      - if: ${{ !cancelled() }}
        run: |
          reviewdog \
            -name="Detekt" \
            -f=sarif \
            -reporter=github-pr-review \
            -filter-mode=file \
            < merged-detekt.sarif
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: yumemi-inc/comment-pull-request@v1
        if: cancelled() != true
        with:
          comment-if-failure: |
            > [!CAUTION]
            > There was a problem with the **Detekt** check. See details [here](${{ env.LOG_URL }}) or run `./gradlew detekt` in local.

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v3
        with:
          cache-read-only: false
      - run: ./gradlew test
      - uses: actions/github-script@v7
        with:
          script: require("${{ github.workspace }}/.github/workflows/pull-request-check.yaml")
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: "unit-test-reports"
          path: |
            build/build-outputs/unit-test-report
      - name: Comment Pull Request
        uses: yumemi-inc/comment-pull-request@v1
        if: cancelled() != true
        with:
          comment-if-failure: |
            > [!CAUTION]
            > There was a problem with the **Unit Test** check. See details [here](${{ env.LOG_URL }}).
            > Or check test report from [here](https://$owner_name.github.io/$repo_name/pr/${{ github.event.pull_request.number }}/unit-test/).

  deploy-unit-test-report:
    needs: [unit-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write # for peaceiris/actions-gh-pages
      pull-requests: write # for yumemi-inc/comment-pull-request
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "unit-test-reports"
          path: build/build-outputs/unit-test-report
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/build-outputs/unit-test-report
          destination_dir: ./pr/${{ github.event.pull_request.number }}/unit-test/
          keep_files: true

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variants:
          - debug
          - release
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v3
        with:
          cache-read-only: false
      - run: ./gradlew :app:assemble${{ matrix.variants }}
      - uses: yumemi-inc/comment-pull-request@v1
        if: cancelled() != true
        with:
          comment-if-failure: |
            > [!CAUTION]
            > There was a problem with the **${{ matrix.variants }} Build** check. See details [here](${{ env.LOG_URL }}) or run `./gradlew :app:assemble${{ matrix.variants }}` in local.
